BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Blitz" (
	"blitzid"	INTEGER,
	"theme"	TEXT NOT NULL UNIQUE,
	"difficult"	INTEGER DEFAULT 0,
	PRIMARY KEY("blitzid" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Larks" (
	"larkid"	INTEGER,
	"theme"	TEXT NOT NULL UNIQUE,
	"difficult"	INTEGER DEFAULT 0,
	PRIMARY KEY("larkid" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Owls" (
	"owlid"	INTEGER,
	"theme"	TEXT NOT NULL UNIQUE,
	"difficult"	INTEGER DEFAULT 0,
	PRIMARY KEY("owlid" AUTOINCREMENT)
);
COMMIT;
